services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fpl-server
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./server:/usr/src/app
    networks:
      - fpl-net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: fpl-client
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - fpl-net

  predict:
    build:
      context: ./predict
      dockerfile: Dockerfile
    container_name: fpl-predict
    ports:
      - '5001:5000'
    volumes:
      - ./predict:/app
    networks:
      - fpl-net

  prometheus:
    container_name: fpl-prometheus
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus-data:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - server
    networks:
      - fpl-net

  grafana:
    container_name: fpl-grafana
    image: grafana/grafana
    ports:
      - '4000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_DASHBBOARDS_DEFAULT_PATH=/var/lib/grafana/dashboards
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - fpl-net

networks:
  fpl-net:

volumes:
  prometheus-data:
  grafana-data:
