{
 "title": "Fantasy Premier League",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests Duration",
   "type": "histogram",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "api_request_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Successful",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "api_requests_successful", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Failed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "api_requests_failed", "legendFormat": "__auto" }
   ]
  }
 ]
}